general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  startup_commands: []

  # Commands to run just before the WM is shutdown.
  shutdown_commands: []

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: true

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'monitor_focus'

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: 'cloak'

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: true

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: '10px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '10px'
    right: '10px'
    bottom: '10px'
    left: '10px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: '#8dbcff'

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'square'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: 'square'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: '1'
    bind_to_monitor: 0
    keep_alive: true
  - name: '2'
    bind_to_monitor: 0
    keep_alive: true
  - name: '3'
    bind_to_monitor: 0
    keep_alive: true
  - name: '4'
    bind_to_monitor: 1
    keep_alive: true
  - name: '5'
    bind_to_monitor: 1
    keep_alive: true
  - name: '6'
    bind_to_monitor: 1
    keep_alive: true

window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }

  # fix for screen snipping/snip and sketch/win+s screenshot key
      - window_title: { equals: "Screen Snipping" }
      - window_title: { equals: "Snipping Tool" }
      - window_process: { equals: "ScreenSketch" }
      - window_process: { equals: "ScreenClippingHost" }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['lwin+h', 'lwin+left', 'rwin+h', 'rwin+left']
  - commands: ['focus --direction right']
    bindings: ['lwin+l', 'lwin+right', 'rwin+l', 'rwin+right']
  - commands: ['focus --direction up']
    bindings: ['lwin+k', 'lwin+up', 'rwin+k', 'rwin+up']
  - commands: ['focus --direction down']
    bindings: ['lwin+j', 'lwin+down', 'rwin+j', 'rwin+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['lwin+shift+h', 'lwin+shift+left', 'rwin+shift+h', 'rwin+shift+left']
  - commands: ['move --direction right']
    bindings: ['lwin+shift+l', 'lwin+shift+right', 'rwin+shift+l', 'rwin+shift+right']
  - commands: ['move --direction up']
    bindings: ['lwin+shift+k', 'lwin+shift+up', 'rwin+shift+k', 'rwin+shift+up']
  - commands: ['move --direction down']
    bindings: ['lwin+shift+j', 'lwin+shift+down', 'rwin+shift+j', 'rwin+shift+down']

  # Resize focused window by a percentage or pixel amount.
  #- commands: ['resize --width -2%']
  #  bindings: ['alt+u']
  #- commands: ['resize --width +2%']
  #  bindings: ['alt+p']
  #- commands: ['resize --height +2%']
  #  bindings: ['alt+o']
  #- commands: ['resize --height -2%']
  #  bindings: ['alt+i']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  #- commands: ['wm-enable-binding-mode --name resize']
  #  bindings: ['alt+r']

  # Disables window management and all other keybindings until alt+shift+p
  # is pressed again.
  #- commands: ['wm-toggle-pause']
  #  bindings: ['alt+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['lwin+8', 'rwin+8']

  # Change focus from tiling windows -> floating -> fullscreen.
  #- commands: ['wm-cycle-focus']
  #  bindings: ['alt+space']

  # Change the focused window to be floating.
  #- commands: ['toggle-floating --centered']
  #  bindings: ['alt+shift+space']

  # Change the focused window to be tiling.
  #- commands: ['toggle-tiling']
  # bindings: ['alt+t']

  # Change the focused window to be fullscreen.
  #- commands: ['toggle-fullscreen']
  # bindings: ['alt+f']

  # Minimize focused window.
  #- commands: ['toggle-minimized']
  # bindings: ['alt+m']

  # Close focused window.
  - commands: ['close']
    bindings: ['lwin+c', 'rwin+c']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['lwin+q', 'rwin+q']

  # Re-evaluate configuration file.
  #- commands: ['wm-reload-config']
  #  bindings: ['alt+shift+r']

  # Redraw all windows.
  #- commands: ['wm-redraw']
  #  bindings: ['alt+shift+w']

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ['shell-exec alacritty']
    bindings: ['alt+control+t']

  # Focus the next/previous active workspace defined in `workspaces` config.
  #- commands: ['focus --next-active-workspace']
  #  bindings: ['alt+s']
  #- commands: ['focus --prev-active-workspace']
  #  bindings: ['alt+a']

  # Focus the workspace that last had focus.
  #- commands: ['focus --recent-workspace']
  #  bindings: ['lwin+tab']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['lwin+1', 'rwin+1']
  - commands: ['focus --workspace 2']
    bindings: ['lwin+2', 'rwin+2']
  - commands: ['focus --workspace 3']
    bindings: ['lwin+3', 'rwin+3']
  - commands: ['focus --workspace 4']
    bindings: ['lwin+4', 'rwin+4']
  - commands: ['focus --workspace 5']
    bindings: ['lwin+5', 'rwin+5']
  - commands: ['focus --workspace 6']
    bindings: ['lwin+6', 'rwin+6']

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['lwin+shift+a', 'rwin+shift+a']
  - commands: ['move-workspace --direction right']
    bindings: ['lwin+shift+f', 'rwin+shift+f']
  - commands: ['move-workspace --direction up']
    bindings: ['lwin+shift+d', 'rwin+shift+d']
  - commands: ['move-workspace --direction down']
    bindings: ['lwin+shift+s', 'rwin+shift+s']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['lwin+shift+1', 'rwin+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['lwin+shift+2', 'rwin+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['lwin+shift+3', 'rwin+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['lwin+shift+4', 'rwin+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['lwin+shift+5', 'rwin+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['lwin+shift+6', 'rwin+shift+6']

  # Call ms-screenclip: manually because normal shortcut broken
  - commands: ['shell-exec ms-screenclip:']
    bindings: ['lwin+shift+s', 'rwin+shift:s']
